# tmux source-file ~/.tmux.conf 重新加载

# -- 基础设置优化 --
# 更改前缀键为 Ctrl+a
# set -g prefix C-a
#unbind C-b
#bind C-a send-prefix

# 降低按键延迟，防止 Vim 等应用卡顿
set -sg escape-time 1

# -- 复制模式优化 --
# 绑定 Prefix + v 进入复制模式，q 退出
bind v copy-mode
# 启用 Vi 风格
setw -g mode-keys vi
# v 开始选择，y 复制并退出
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# (可选) 鼠标滚动自动进入复制模式
set -g mouse on

